name: CI - user-service
on:
  push:
    paths:
      - 'services/user-service/**'
      - '.github/workflows/ci-user.yml'
  pull_request:
    paths:
      - 'services/user-service/**'
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: usersdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=5s --health-timeout=3s --health-retries=10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        working-directory: services/user-service
        run: npm ci
      - name: Wait for MySQL
        run: |
          for i in {1..60}; do
            nc -z 127.0.0.1 3306 && echo "mysql up" && break
            sleep 2
          done
      - name: Run tests
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PASSWORD: rootpass
          MYSQL_DB: usersdb
          JWT_SECRET: devjwt
        working-directory: services/user-service
        run: npm test --silent
      - name: Docker build
        working-directory: services/user-service
        run: docker build -t user-service:ci .
